version: "3.9"

services:
  db:
    image: postgres:alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Vending!123
  web:
    build: .
    #    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/static

    ports:
      - "8000:8000"
    environment:
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=Vending!123
      - DB_PORT=5432
      - DB_HOST=db
      - DJANGO_SECRET_KEY=django-insecure-xebb^suk7-30&on-rj5v*kpn+=7mx-pva%*o@3i3(wewn8hqlt
    depends_on:
      - db

  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
    depends_on:
      - web
    restart: "on-failure"

volumes:
  postgres_data:
  static_volume:
