# Generated by Django 4.1.1 on 2022-09-11 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Post title')),
                ('content', models.TextField(verbose_name='Post Content')),
                ('slug', models.CharField(max_length=255, verbose_name='Post slug')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Event Version')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Published'), (1, 'Draft'), (2, 'Archived'), (3, 'Deleted')])),
                ('action_by', models.PositiveIntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'User Post',
                'verbose_name_plural': 'User Posts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict, verbose_name='Data')),
                ('event_type', models.CharField(choices=[('PUBLISH', 'Publish'), ('DRAFT', 'Draft'), ('CREATED', 'Created'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], max_length=100)),
                ('aggregate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='publishing.post')),
            ],
            options={
                'verbose_name': 'Post Event',
                'verbose_name_plural': 'Posts Events',
                'ordering': ['created_at'],
            },
        ),
    ]
