# Generated by Django 4.1.1 on 2022-09-12 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_alter_post_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
