# Generated by Django 4.1.1 on 2022-09-13 22:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publishing', '0005_subscribe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscribe',
            unique_together={('subscriber', 'subscribe_to')},
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='event_type',
        ),
    ]
