# Generated by Django 4.1.1 on 2022-09-12 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_interests_user_birth_date_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interests',
            new_name='Interest',
        ),
    ]
